// SPDX-License-Identifier: GPL-3.0-or-later

// steer-ui-spec generates the build-time UI contract consumed by LuCI,
// Linux Web and the native macOS application. It is not a shipped CLI.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/gsh20040816/steer/go/internal/uispec"
)

func main() {
	root := flag.String("root", "..", "repository root")
	check := flag.Bool("check", false, "fail if generated files differ")
	flag.Parse()
	if flag.NArg() != 0 {
		fatal(errors.New("ui spec generator accepts flags only"))
	}
	encoded, err := json.MarshalIndent(uispec.ContractValue(), "", "  ")
	if err != nil {
		fatal(err)
	}
	encoded = append(encoded, '\n')
	outputs := map[string][]byte{
		"ui/steer-ui-spec.json":                                        encoded,
		"go/cmd/steer-linux/web/js/ui-spec.js":                         []byte("/* Code generated by steer-ui-spec; DO NOT EDIT. */\n'use strict';\n(function () { window.S = window.S || {}; window.S.uiSpec = " + string(bytes.TrimSpace(encoded)) + "; })();\n"),
		"luci-app-steer/htdocs/luci-static/resources/steer/ui-spec.js": []byte("/* Code generated by steer-ui-spec; DO NOT EDIT. */\n'use strict';\n'require baseclass';\nreturn baseclass.extend(" + string(bytes.TrimSpace(encoded)) + ");\n"),
		"macos/SteerApp/GeneratedUISpec.swift":                         []byte("// Code generated by steer-ui-spec; DO NOT EDIT.\nimport Foundation\n\nenum GeneratedUISpec {\n    static let document = #\"\"\"\n" + string(bytes.TrimSpace(encoded)) + "\n\"\"\"#\n}\n"),
	}
	for relative, content := range outputs {
		path := filepath.Join(*root, filepath.FromSlash(relative))
		if *check {
			current, readErr := os.ReadFile(path)
			if readErr != nil || !bytes.Equal(current, content) {
				fatal(fmt.Errorf("generated UI contract is stale: %s", relative))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fatal(err)
		}
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
