// SPDX-License-Identifier: GPL-3.0-or-later

import NetworkExtension

/// DNS capture is intentionally separate from PacketTunnelProvider. The
/// first implementation will forward only NEDNSProxyFlow DNS messages to the
/// dedicated localhost inbound generated by SteerCore.
final class DNSProxyProvider: NEDNSProxyProvider {
    override func startProxy(options: [String: Any]?, completionHandler: @escaping (Error?) -> Void) {
        // Load the generation selected by the App Group coordinator here.
        completionHandler(DNSProxyProviderError.runtimePending)
    }

    override func stopProxy(with reason: NEProviderStopReason, completionHandler: @escaping () -> Void) {
        completionHandler()
    }

    override func handleNewFlow(_ flow: NEAppProxyFlow) -> Bool {
        // UDP/TCP framing and loopback forwarding are deliberately not
        // silently dropped in this placeholder. Returning false asks the OS
        // to reject the flow until a signed, tested implementation is wired.
        return false
    }
}

private enum DNSProxyProviderError: Error {
    case runtimePending
}
