/* Code generated by steer-ui-spec; DO NOT EDIT. */
'use strict';
(function () { window.S = window.S || {}; window.S.uiSpec = {
  "schema_version": 1,
  "canonical_schema": 9,
  "node_types": [
    {
      "value": "socks",
      "label": "SOCKS"
    },
    {
      "value": "http",
      "label": "HTTP CONNECT"
    },
    {
      "value": "shadowsocks",
      "label": "Shadowsocks"
    },
    {
      "value": "vmess",
      "label": "VMess"
    },
    {
      "value": "vless",
      "label": "VLESS"
    },
    {
      "value": "trojan",
      "label": "Trojan"
    },
    {
      "value": "hysteria",
      "label": "Hysteria"
    },
    {
      "value": "hysteria2",
      "label": "Hysteria2"
    },
    {
      "value": "shadowtls",
      "label": "ShadowTLS"
    },
    {
      "value": "tuic",
      "label": "TUIC"
    },
    {
      "value": "anytls",
      "label": "AnyTLS"
    },
    {
      "value": "naive",
      "label": "NaiveProxy"
    },
    {
      "value": "ssh",
      "label": "SSH"
    },
    {
      "value": "tor",
      "label": "Tor"
    }
  ],
  "node_fields": [
    {
      "key": "enabled",
      "label": "Enabled",
      "control": "boolean",
      "section": "general",
      "types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh",
        "tor"
      ],
      "default": true
    },
    {
      "key": "name",
      "label": "Name",
      "control": "text",
      "section": "general",
      "types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh",
        "tor"
      ],
      "required_types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh",
        "tor"
      ]
    },
    {
      "key": "server",
      "label": "Server",
      "control": "text",
      "section": "general",
      "types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh"
      ],
      "required_types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh"
      ],
      "placeholder": "example.com or IP"
    },
    {
      "key": "server_port",
      "label": "Port",
      "control": "integer",
      "section": "general",
      "types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh"
      ],
      "required_types": [
        "socks",
        "http",
        "shadowsocks",
        "vmess",
        "vless",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh"
      ],
      "default": 443
    },
    {
      "key": "uuid",
      "label": "UUID",
      "control": "text",
      "section": "protocol",
      "types": [
        "vmess",
        "vless",
        "tuic"
      ],
      "required_types": [
        "vmess",
        "vless",
        "tuic"
      ]
    },
    {
      "key": "username",
      "label": "Username",
      "control": "text",
      "section": "protocol",
      "types": [
        "socks",
        "http",
        "naive",
        "ssh"
      ],
      "required_types": [
        "ssh"
      ]
    },
    {
      "key": "password",
      "label": "Password",
      "control": "password",
      "section": "protocol",
      "types": [
        "socks",
        "http",
        "shadowsocks",
        "trojan",
        "hysteria",
        "hysteria2",
        "shadowtls",
        "tuic",
        "anytls",
        "naive",
        "ssh"
      ],
      "required_types": [
        "shadowsocks",
        "trojan",
        "hysteria",
        "hysteria2",
        "tuic",
        "anytls",
        "naive"
      ],
      "sensitive": true
    },
    {
      "key": "method",
      "label": "Method",
      "control": "text",
      "section": "protocol",
      "types": [
        "shadowsocks"
      ],
      "required_types": [
        "shadowsocks"
      ],
      "placeholder": "2022-blake3-aes-128-gcm"
    },
    {
      "key": "plugin",
      "label": "Plugin",
      "control": "select",
      "section": "protocol",
      "types": [
        "shadowsocks"
      ],
      "options": [
        {
          "value": "",
          "label": "None"
        },
        {
          "value": "obfs-local",
          "label": "obfs-local"
        },
        {
          "value": "v2ray-plugin",
          "label": "v2ray-plugin"
        }
      ]
    },
    {
      "key": "plugin_options",
      "label": "Plugin options",
      "control": "text",
      "section": "protocol",
      "types": [
        "shadowsocks"
      ]
    },
    {
      "key": "security",
      "label": "Security",
      "control": "select",
      "section": "protocol",
      "types": [
        "vmess"
      ],
      "options": [
        {
          "value": "",
          "label": "Default"
        },
        {
          "value": "auto",
          "label": "auto"
        },
        {
          "value": "none",
          "label": "none"
        },
        {
          "value": "zero",
          "label": "zero"
        },
        {
          "value": "aes-128-gcm",
          "label": "aes-128-gcm"
        },
        {
          "value": "chacha20-poly1305",
          "label": "chacha20-poly1305"
        },
        {
          "value": "aes-128-ctr",
          "label": "aes-128-ctr"
        }
      ]
    },
    {
      "key": "alter_id",
      "label": "Alter ID",
      "control": "integer",
      "section": "protocol",
      "types": [
        "vmess"
      ]
    },
    {
      "key": "network",
      "label": "Network",
      "control": "select",
      "section": "protocol",
      "types": [
        "vmess"
      ],
      "options": [
        {
          "value": "",
          "label": "Default"
        },
        {
          "value": "tcp",
          "label": "TCP"
        },
        {
          "value": "udp",
          "label": "UDP"
        }
      ]
    },
    {
      "key": "packet_encoding",
      "label": "UDP packet encoding",
      "control": "select",
      "section": "protocol",
      "types": [
        "vmess",
        "vless"
      ],
      "options": [
        {
          "value": "",
          "label": "Default"
        },
        {
          "value": "xudp",
          "label": "XUDP"
        },
        {
          "value": "packetaddr",
          "label": "PacketAddr"
        }
      ]
    },
    {
      "key": "flow",
      "label": "Flow",
      "control": "select",
      "section": "protocol",
      "types": [
        "vless"
      ],
      "options": [
        {
          "value": "",
          "label": "None"
        },
        {
          "value": "xtls-rprx-vision",
          "label": "XTLS Vision"
        }
      ]
    },
    {
      "key": "transport",
      "label": "Transport",
      "control": "select",
      "section": "transport",
      "types": [
        "vmess",
        "vless",
        "trojan"
      ],
      "options": [
        {
          "value": "tcp",
          "label": "TCP / Raw"
        },
        {
          "value": "ws",
          "label": "WebSocket"
        },
        {
          "value": "grpc",
          "label": "gRPC"
        },
        {
          "value": "http",
          "label": "HTTP"
        },
        {
          "value": "quic",
          "label": "QUIC"
        }
      ],
      "default": "tcp"
    },
    {
      "key": "transport_path",
      "label": "Transport path",
      "control": "text",
      "section": "transport",
      "types": [
        "vmess",
        "vless",
        "trojan"
      ],
      "when": {
        "field": "transport",
        "values": [
          "ws",
          "http"
        ]
      },
      "placeholder": "/path"
    },
    {
      "key": "transport_host",
      "label": "Transport host",
      "control": "text",
      "section": "transport",
      "types": [
        "vmess",
        "vless",
        "trojan"
      ],
      "when": {
        "field": "transport",
        "values": [
          "ws",
          "http"
        ]
      },
      "placeholder": "example.com"
    },
    {
      "key": "service_name",
      "label": "gRPC service name",
      "control": "text",
      "section": "transport",
      "types": [
        "vmess",
        "vless",
        "trojan"
      ],
      "when": {
        "field": "transport",
        "values": [
          "grpc"
        ]
      }
    },
    {
      "key": "server_ports",
      "label": "Port hopping ranges",
      "control": "string-list",
      "section": "protocol",
      "types": [
        "hysteria",
        "hysteria2"
      ],
      "placeholder": "20000:21000"
    },
    {
      "key": "hop_interval",
      "label": "Port hopping interval",
      "control": "text",
      "section": "protocol",
      "types": [
        "hysteria",
        "hysteria2"
      ],
      "placeholder": "30s"
    },
    {
      "key": "obfs_type",
      "label": "Obfuscation",
      "control": "select",
      "section": "protocol",
      "types": [
        "hysteria2"
      ],
      "options": [
        {
          "value": "",
          "label": "None"
        },
        {
          "value": "salamander",
          "label": "Salamander"
        }
      ]
    },
    {
      "key": "obfs_password",
      "label": "Obfuscation password",
      "control": "password",
      "section": "protocol",
      "types": [
        "hysteria",
        "hysteria2"
      ],
      "sensitive": true
    },
    {
      "key": "up_mbps",
      "label": "Upload Mbps",
      "control": "integer",
      "section": "protocol",
      "types": [
        "hysteria",
        "hysteria2"
      ],
      "required_types": [
        "hysteria"
      ]
    },
    {
      "key": "down_mbps",
      "label": "Download Mbps",
      "control": "integer",
      "section": "protocol",
      "types": [
        "hysteria",
        "hysteria2"
      ],
      "required_types": [
        "hysteria"
      ]
    },
    {
      "key": "version",
      "label": "Version",
      "control": "select-integer",
      "section": "protocol",
      "types": [
        "shadowtls"
      ],
      "options": [
        {
          "value": "1",
          "label": "1"
        },
        {
          "value": "2",
          "label": "2"
        },
        {
          "value": "3",
          "label": "3"
        }
      ],
      "default": 3
    },
    {
      "key": "congestion_control",
      "label": "Congestion control",
      "control": "select",
      "section": "protocol",
      "types": [
        "tuic"
      ],
      "options": [
        {
          "value": "",
          "label": "Default"
        },
        {
          "value": "cubic",
          "label": "cubic"
        },
        {
          "value": "new_reno",
          "label": "new_reno"
        },
        {
          "value": "bbr",
          "label": "bbr"
        }
      ]
    },
    {
      "key": "udp_relay_mode",
      "label": "UDP relay mode",
      "control": "select",
      "section": "protocol",
      "types": [
        "tuic"
      ],
      "options": [
        {
          "value": "",
          "label": "Default"
        },
        {
          "value": "native",
          "label": "native"
        },
        {
          "value": "quic",
          "label": "quic"
        }
      ]
    },
    {
      "key": "udp_over_stream",
      "label": "UDP over stream",
      "control": "boolean",
      "section": "protocol",
      "types": [
        "tuic"
      ]
    },
    {
      "key": "zero_rtt_handshake",
      "label": "0-RTT handshake",
      "control": "boolean",
      "section": "advanced",
      "types": [
        "tuic"
      ]
    },
    {
      "key": "heartbeat",
      "label": "Heartbeat",
      "control": "text",
      "section": "advanced",
      "types": [
        "tuic"
      ],
      "placeholder": "10s"
    },
    {
      "key": "quic",
      "label": "QUIC",
      "control": "boolean",
      "section": "advanced",
      "types": [
        "naive"
      ]
    },
    {
      "key": "quic_congestion_control",
      "label": "QUIC congestion control",
      "control": "select",
      "section": "advanced",
      "types": [
        "naive"
      ],
      "options": [
        {
          "value": "",
          "label": "Default"
        },
        {
          "value": "bbr",
          "label": "bbr"
        },
        {
          "value": "bbr2",
          "label": "bbr2"
        },
        {
          "value": "cubic",
          "label": "cubic"
        },
        {
          "value": "reno",
          "label": "reno"
        }
      ]
    },
    {
      "key": "insecure_concurrency",
      "label": "Insecure concurrency",
      "control": "integer",
      "section": "advanced",
      "types": [
        "naive"
      ]
    },
    {
      "key": "private_key",
      "label": "Private key",
      "control": "password",
      "section": "protocol",
      "types": [
        "ssh"
      ],
      "sensitive": true,
      "multiline": true
    },
    {
      "key": "host_key",
      "label": "Host key",
      "control": "text",
      "section": "protocol",
      "types": [
        "ssh"
      ]
    },
    {
      "key": "host_key_algorithms",
      "label": "Host key algorithms",
      "control": "string-list",
      "section": "protocol",
      "types": [
        "ssh"
      ],
      "placeholder": "ssh-ed25519, rsa-sha2-512"
    },
    {
      "key": "executable_path",
      "label": "Executable path",
      "control": "text",
      "section": "protocol",
      "types": [
        "tor"
      ]
    },
    {
      "key": "extra_args",
      "label": "Extra arguments",
      "control": "string-list",
      "section": "protocol",
      "types": [
        "tor"
      ]
    },
    {
      "key": "data_directory",
      "label": "Data directory",
      "control": "text",
      "section": "protocol",
      "types": [
        "tor"
      ]
    },
    {
      "key": "tls_server_name",
      "label": "TLS server name",
      "control": "text",
      "section": "tls",
      "types": [
        "http",
        "vmess",
        "hysteria",
        "vless",
        "hysteria2",
        "trojan",
        "shadowtls",
        "tuic",
        "anytls",
        "naive"
      ],
      "required_types": [
        "hysteria",
        "hysteria2",
        "trojan",
        "shadowtls",
        "tuic",
        "anytls",
        "naive"
      ],
      "placeholder": "server.example.com"
    },
    {
      "key": "utls_fingerprint",
      "label": "uTLS fingerprint",
      "control": "select",
      "section": "tls",
      "types": [
        "http",
        "vmess",
        "hysteria",
        "vless",
        "hysteria2",
        "trojan",
        "shadowtls",
        "tuic",
        "anytls",
        "naive"
      ],
      "options": [
        {
          "value": "",
          "label": "System default"
        },
        {
          "value": "chrome",
          "label": "chrome"
        },
        {
          "value": "firefox",
          "label": "firefox"
        },
        {
          "value": "safari",
          "label": "safari"
        },
        {
          "value": "edge",
          "label": "edge"
        },
        {
          "value": "random",
          "label": "random"
        }
      ]
    },
    {
      "key": "insecure",
      "label": "Skip certificate verification",
      "control": "boolean",
      "section": "tls",
      "types": [
        "http",
        "vmess",
        "hysteria",
        "vless",
        "hysteria2",
        "trojan",
        "shadowtls",
        "tuic",
        "anytls",
        "naive"
      ]
    },
    {
      "key": "reality_public_key",
      "label": "REALITY public key",
      "control": "text",
      "section": "tls",
      "types": [
        "vless"
      ]
    },
    {
      "key": "reality_short_id",
      "label": "REALITY short ID",
      "control": "text",
      "section": "tls",
      "types": [
        "vless"
      ]
    }
  ],
  "log_levels": [
    {
      "value": "error",
      "label": "Error"
    },
    {
      "value": "warn",
      "label": "Warning"
    },
    {
      "value": "info",
      "label": "Info"
    },
    {
      "value": "debug",
      "label": "Debug"
    }
  ],
  "bootstrap_protocols": [
    {
      "value": "udp",
      "label": "UDP"
    },
    {
      "value": "tcp",
      "label": "TCP"
    }
  ],
  "bootstrap_strategies": [
    {
      "value": "prefer_ipv4",
      "label": "Prefer IPv4"
    },
    {
      "value": "prefer_ipv6",
      "label": "Prefer IPv6"
    },
    {
      "value": "ipv4_only",
      "label": "IPv4 only"
    },
    {
      "value": "ipv6_only",
      "label": "IPv6 only"
    }
  ],
  "route_kinds": [
    {
      "value": "direct",
      "label": "Direct"
    },
    {
      "value": "block",
      "label": "Reject"
    },
    {
      "value": "single",
      "label": "Single node"
    }
  ],
  "dns_protocols": [
    {
      "value": "udp",
      "label": "UDP"
    },
    {
      "value": "tcp",
      "label": "TCP"
    },
    {
      "value": "tls",
      "label": "DoT"
    },
    {
      "value": "https",
      "label": "DoH"
    },
    {
      "value": "quic",
      "label": "DoQ"
    },
    {
      "value": "h3",
      "label": "DoH3"
    }
  ],
  "local_proxy_protocols": [
    {
      "value": "mixed",
      "label": "Mixed (SOCKS + HTTP)"
    },
    {
      "value": "socks",
      "label": "SOCKS"
    },
    {
      "value": "http",
      "label": "HTTP CONNECT"
    }
  ],
  "rule_networks": [
    {
      "value": "tcp",
      "label": "TCP"
    },
    {
      "value": "udp",
      "label": "UDP"
    }
  ],
  "rule_protocols": [
    {
      "value": "tls",
      "label": "TLS"
    },
    {
      "value": "http",
      "label": "HTTP"
    },
    {
      "value": "quic",
      "label": "QUIC"
    },
    {
      "value": "dns",
      "label": "DNS"
    },
    {
      "value": "stun",
      "label": "STUN"
    },
    {
      "value": "bittorrent",
      "label": "BitTorrent"
    },
    {
      "value": "dtls",
      "label": "DTLS"
    },
    {
      "value": "ssh",
      "label": "SSH"
    },
    {
      "value": "rdp",
      "label": "RDP"
    },
    {
      "value": "ntp",
      "label": "NTP"
    }
  ],
  "rule_match_fields": [
    "inbound",
    "domain_match",
    "ip_match",
    "source_ip_cidr",
    "source_mac_address",
    "network",
    "protocol",
    "port"
  ],
  "domain_prefixes": [
    "full:",
    "domain:",
    "regexp:",
    "geosite:"
  ],
  "ip_prefixes": [
    "geoip:"
  ],
  "platform_capabilities": {
    "linux": {
      "raw_editor": true,
      "source_mac": true,
      "system_components": false
    },
    "macos": {
      "raw_editor": true,
      "source_mac": false,
      "system_components": true
    },
    "openwrt": {
      "raw_editor": false,
      "source_mac": true,
      "system_components": false
    }
  },
  "navigation": [
    {
      "key": "status",
      "label": "Status",
      "items": [
        {
          "key": "overview",
          "label": "Overview"
        }
      ]
    },
    {
      "key": "configuration",
      "label": "Configuration",
      "items": [
        {
          "key": "general",
          "label": "General"
        },
        {
          "key": "nodes",
          "label": "Nodes"
        },
        {
          "key": "routes",
          "label": "Routes"
        },
        {
          "key": "dns",
          "label": "DNS Profiles"
        },
        {
          "key": "proxies",
          "label": "Local Proxies"
        },
        {
          "key": "rules",
          "label": "Rules"
        }
      ]
    },
    {
      "key": "services",
      "label": "Services",
      "items": [
        {
          "key": "subscriptions",
          "label": "Subscriptions"
        },
        {
          "key": "diagnostics",
          "label": "Diagnostics"
        },
        {
          "key": "system",
          "label": "System"
        }
      ]
    },
    {
      "key": "advanced",
      "label": "Advanced",
      "items": [
        {
          "key": "advanced",
          "label": "Advanced Configuration"
        }
      ]
    }
  ]
}; })();
