#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-3.0-or-later

START=100
STOP=9
USE_PROCD=1

steer_enabled() {
	config_load steer
	local enabled
	config_get_bool enabled main enabled 0
	[ "$enabled" = 1 ]
}

# Keep the scheduler subject to the same install and boot authority as Steer.
enable() {
	steer_enabled || return 0
	local name err=1
	name="$(basename "$initscript")"
	[ -z "$START" ] || { ln -sf "../init.d/$name" "$IPKG_INSTROOT/etc/rc.d/S${START}${name##S[0-9][0-9]}" && err=0; }
	[ -z "$STOP" ] || { ln -sf "../init.d/$name" "$IPKG_INSTROOT/etc/rc.d/K${STOP}${name##K[0-9][0-9]}" && err=0; }
	return "$err"
}

enabled() {
	steer_enabled || return 1
	local name
	name="$(basename "$initscript")"
	{ [ -z "$START" ] || [ -L "$IPKG_INSTROOT/etc/rc.d/S${START}${name##S[0-9][0-9]}" ]; } &&
		{ [ -z "$STOP" ] || [ -L "$IPKG_INSTROOT/etc/rc.d/K${STOP}${name##K[0-9][0-9]}" ]; }
}

start_service() {
	steer_enabled || return 0
	procd_open_instance scheduler
	procd_set_param command /usr/libexec/steer/geodata schedule
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
